### ISSUE TITLE
Use maximum of instance number and percentage for on-demand instances to be kept

### ISSUE THREAD

**Issue by cristim** [AutoSpotting/AutoSpotting#117]
# Github issue #

## Issue type ##

- Feature Idea

## Summary ##

The algorithm currently only considers the absolute number of on-demand instances, ignoring the percentage if an absolute number is given. Ideally it should keep the maximum between the absolute number and the number obtained by computing the percentage, regardless if the higher number comes from group tags or from the default value set in the stack parameters.

## Steps to reproduce ##

- Enable AutoSpotting on a group of 4 on-demand instances
- Set the on-demand number to 1 in the stack parameters and an on-demand percentage to 50% on the group tags

## Expected results ##

The maximum value of instances would be kept, in this case 2 on-demand instances, which are 50% of the group capacity

## Actual results ##

A single on-demand instance is kept.

**Comment by ahaverbuch** [comment]
Was there a solution yet for the scale down scenario? i.e. if hose 2 on-demand (from actual results) was scaled down as being oldest (if that's your scale policy), will it bring an on-demand back?

**Comment by cristim** [comment]
@ahaverbuch Not sure I understand the question and/or how it relates to this issue, please explain on gitter.

**Comment by cristim** [comment]
@ahaverbuch I think I get it now, this is more or less what you reported on #104, right?

I didn't test but I expect the spot instances to be terminated one by one and replaced by AutoScaling with on-demand instances after they are terminated.

AutoSpotting may be changed to increase the group capacity to compensate for lost on-demand capacity and once the on-demand instance is out of its grace period it could detach and terminate the corresponding spot instances.

**Comment by ahaverbuch** [comment]
@cristim  - yep #104 is what I was thinking of when I saw this. Given work on this one (117) to respect the minimum on-demand number that's greatest, (104) would help make sure the minimum is actually always kept.

**Comment by cristim** [comment]
Once this one is solved we would try to keep the largest value between the absolute number and the percentage, but not necessarily without temporary downtime, which was your concern on #104.

Let's continue this downtime-related discussion on #104, since that's where it belongs.

**Comment by pabloroz** [comment]
@cristim the description seems very accurate to what I was asking on gitter, and what I was looking for

**Comment by xlr-8** [comment]
I'm not sure why should this be the default behavior when specifying 1 of those 2 parameters?

**Comment by xlr-8** [comment]
@pabloroz @cristim UP on this issue, if you could explain further it would be great.

My original idea on this feature was that the most "defined number" (e.g. specific value vs percentage) would be used, and allowing overriding those by ASG would allow better control about what/how many instances one would like to replace.

**Comment by cristim** [comment]
I think the absolute numbers are not so reliable if using load-based AutoScaling policies, so if your capacity slowly doubles over time because of load you may want to also double the number of on-demand nodes in the group when using this feature.

I also think that if I set globally a number and locally a percentage, the percentage should take precedence over the absolute value set globally.

Now that I think about it, I guess the maximum between local/global configs may be a bit wasteful.

**Comment by xlr-8** [comment]
> I think the absolute numbers are not so reliable if using load-based AutoScaling policies, so if your capacity slowly doubles over time because of load you may want to also double the number of on-demand nodes in the group when using this feature.

Then use percentages, not absolute number.

> I also think that if I set globally a number and locally a percentage, the percentage should take precedence over the absolute value set globally.

What you describe is the expected behavior.

Example cases:

1. If you had set X spot instances on your ASG, it's because you would know you need exactly X instances, not more not less. So if the ASG scales, shame on you for not configuring autospotting properly.

1.  If you had set an absolute number configured in autospotting, but a percentage in the ASG, then the ASG's configuration would take dominance over the overall configuration.

This behavior/feature has been linked [here](https://github.com/cristim/autospotting/blob/master/TECHNICAL_DETAILS.md#summary-of-supported-features--options) and explainer furthermore [here](https://github.com/cristim/autospotting/blob/master/START.md#minimum-on-demand-configuration), but might require some rewording, if you believe this is not clear please let me know.

**Comment by gabegorelick** [comment]
> Ideally it should keep the maximum between the absolute number and the number obtained by computing the percentage

AWS's OnDemandPercentageAboveBaseCapacity isn't exactly the same, but I think it's a better approach. I've filed #403 to track implementing that.

**Comment by cristim** [comment]
This has recently been implemented in #432

Huge thanks to @jjones-smug of https://SmugMug.com for this contribution to AutoSpotting!
