### ISSUE TITLE
Optional feature: only replace specially tagged instances within the ASG

### ISSUE THREAD

**Issue by wegel** [AutoSpotting/AutoSpotting#155]
## Issue type ##

- Feature Idea

## Summary ##

Have an optional feature where Autospotting wouldn't try to replace an on-demand instance **unless** it's been tagged with something specific.

I would use this mainly to mark instances which are deemed "ready" to be replaced; I have some processes which might take a long (or short, it's completely arbitrary) time to complete on bootstrapping an instance, and getting them replaced before they are fully ready is calling for trouble. Waiting for a pre-defined amount of time is not really an option since the time can vary from a few minutes to a few hours.

**Comment by cristim** [comment]
Thanks for this proposal, I also think it might be useful in some cases.

But I guess not so much for bootstrapping, because the instance will be soon terminated so I don't think it makes much difference if it actually finished the bootstrapping process.

I think a better use case would be to mark the instance as drained by setting such a tag, in case the workload is for example batch processing of relatively large work items taken from a queue.

**Comment by cristim** [comment]
But I just realized such a tag would be indeed useful for bootstrapping but to be set on the spot instances which are ready to be added to the group.

I'm thinking that maybe we could combine these so we only perform the replacement when the on-demand instance is tagged as full drained and at the same time the spot instance is tagged as fully bootstrapped

**Comment by wegel** [comment]
Yes, I think that could be a powerful combination. Maybe a way to specify which of those (on-demand ready, spot ready, or both) to wait on, also.

**Comment by cristim** [comment]
I would prefer to have them configurable independently with different tags, it would also likely simplify the logic, we would not need to explicitly treat each of the cases.

Then it's up to the users to decide which of these is appropriate for them.

**Comment by cristim** [comment]
I think this is now doable using the instance termination protection or scale-in protection. Autospotting will not replace any such protected instances
