### ISSUE TITLE
Command to temporary pause autospotting and terminate unattached instances

### ISSUE THREAD

**Issue by Nyoroon** [AutoSpotting/AutoSpotting#160]
# Github issue #

## Issue type ##

- Feature Idea

## Summary ##

It would be nice to be able to temporary pause autospotting from handling my group to deploy, then resume after.
Like:
```
$ autospotting pause -clean-unattached-instances <group>
$ deploy
$ autospotting resume <group>
```

**Comment by cristim** [comment]
@Nyoroon thanks for this suggestion, this is great for people doing AMI-based deployments.

The pause/resume is trivial to do, by simply setting the spot-enabled tag to true/false. The cleanup of unattached spot instances may need a bit more work, but shouldn't be so hard either.

I'm just thinking that maybe having the enable/disable synonyms or used instead pause/resume would be useful for the initial setup of autospotting on a group and for uninstalling autospotting.

For uninstallation, another cleanup method may be to rolling-terminate the spot instances and revert the group to the fully on-demand initial configuration by simply setting the tag to keep on-demand capacity tag to 100% on all the spot-enabled groups.

**Comment by cristim** [comment]
We now have a way to clean up unattached spot instances, leveraging the relatively recent cron schedule functionality:

`docker -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY run autospotting --cron_schedule_state off --tag_filters tag-matching-your-group=tag-value`
