### ISSUE TITLE
Refactor autospotting code

### ISSUE THREAD

**Issue by xlr-8** [AutoSpotting/AutoSpotting#173]
## Issue type ##

- Feature Idea

## Summary ##

Refactor the code

## Details ##

Following [the functional testing](https://github.com/cristim/autospotting/issues/172) issue, it could be good to consider refactoring the code - now that it has more maturity, testing, documentation & so on.
It would benefit in being better structured, easier to use and test.

But without functional testing, that would be nearly impossible to do - as we wouldn't be able to ensure the behavior remains the same in all known cases.

**Comment by cristim** [comment]
I'm  constantly refactoring the code, pretty much  whenever I have a larger feature that touches a lot of code I try to also change the surrounding areas.

I think we had a couple of large refactorings ever since this issue was raised.
