### ISSUE TITLE
Standardized build/dev environment

### ISSUE THREAD

**Issue by cristim** [AutoSpotting/AutoSpotting#243]
# Github issue #

## Issue type ##

- Feature Idea

## Summary ##

- Implement a Docker-based tool/script that allows non-golang-developers to create custom/local builds without setting up a full-fledged local golang development environment, and also allows developers and TravisCI to use exactly the same build environment.
- Update the documentation accordingly.

**Comment by xlr-8** [comment]
Note quite related but might help eventually: https://github.com/cristim/autospotting/pull/181 - used for testing the vendoring

**Comment by cristim** [comment]
I'm thinking  to make use of multi-stage builds through docker-compose and integrate them into the make targets

**Comment by cristim** [comment]
We now have a Dockerfile and Docker compose configuration for a  standardized build image. We already use it for the TravisCI builds.

**Comment by lenucksi** [comment]
Nice :D
