### ISSUE TITLE
Recent instance types (T3, R5, etc.) are not supported

### ISSUE THREAD

**Issue by cristim** [AutoSpotting/AutoSpotting#294]
# Github issue #

- Bug Report

## Build number #

```text
up to build 929
```

## Configuration ##

- T3, R5, etc. instances as initial instance type set on the ASG
- other on-demand instance types that would normally be replaceable by these recent instance types

## Summary ##

AutoSpotting lacks support for the recent instance types, because we lack spec and/or pricing information for them, which should come from the upstream ec2instances.info instance type database.

## Steps to reproduce ##

- Use AutoSpotting against a group of T3 on-demand instance types with the allowed instances types configuration set to "current". 
and also
- Use AutoSpotting against a group of C5 on-demand instance types with the allowed instances types configuration set to "t3*"

## Expected results ##

For both these cases the groups should be replaced by T3 spot instances.

## Actual results ##

The groups keep running their on-demand nodes, AutoSpotting fails to launch any spot nodes for them.

**Comment by bilalmughal** [comment]
@cristim Since [this](https://github.com/powdahound/ec2instances.info/issues/367) ec2instance.info issue has been resolved. Now it should fetch instance info properly.

**Comment by cristim** [comment]
@bilalmughal thanks for the heads-up, I'll create a new build containing the updated instance type information.

**Comment by cristim** [comment]
@bilalmughal please give #308 a try, this should add support for all recent instance types.

I think as of now we need to manually blacklist the ARM instance types, before we have a way to distinguish them by some attributes.

**Comment by bilalmughal** [comment]
@cristim I can not give it a try as of now. I am on stable build in production and can not do it now.

**Comment by cristim** [comment]
@bilalmughal feel free to take your time, but I'll only merge this once myself or someone else manages to test it and can confirm it  works as expected.
