### ISSUE TITLE
Investigate a workaround for the lack of launch Lifecycle Hooks

### ISSUE THREAD

**Issue by cristim** [AutoSpotting/AutoSpotting#296]
# Github issue #

## Issue type ##

- Feature Idea

## Summary ##

The group lifecycle hooks are not triggered for the spot instances, because they are launched outside the group.

We should try to implement a workaround, perhaps by changing the lifecycle state manually using the `ec2.SetCode` API calls if the group has some lifecycle hooks defined.

We should be careful not to block the launch of instances on groups that don't have any lifecycle hooks configured.

## Steps to reproduce ##

- have a group with lifecycle hooks
- trigger an instance replacement

## Expected results ##

- the lifecycle hook would be triggered when launching the spot instance outside the group

## Actual results ##

- the lifecycle hook is not triggered

**Comment by cristim** [comment]
Thanks @earzur for your comment, I totally agree that lifecycle hooks are often useful for many production use cases.

Currently we do support them out of the box when terminating the on demand instances, but unfortunately for the launched spot instances this is a bit tricky,and we don't have a solution for this at the moment.

If we attach the spot instances right away, like you suggested, they would increase the group capacity so that the Autoscaling group's scaling policies can take action and terminate the new spot instances, unless we protect them from termination for a while(maybe as much as the grace period) or temporarily suspend the scaling processes for the group. Did you test this behavior, I kind of doubt that the lifecycle hooks would run for these spot instances if we attach them immediately.

But I haven't yet tested any of these scenarios and so far I don't know of any way to achieve this without interfering too much with the Autoscaling group.

But by all means please try to test these things and if they hold true I'm very interested to see a PR that changes the current behavior and adds support for the lifecycle hooks for the spot instances as well.

**Comment by cristim** [comment]
@earzur no problem, we can also make the PR, as long as you or someone else can hack the code enough to test and determine the actual behavior.

**Comment by earzur** [comment]
i've been experimenting with this today and my main problem with our current setup (rancher hosts in an ASG, with a container that monitors scale-in events to deactivate the rancher host in the cluster) is that when autospotting takes the decision to move an on-demand instance to spot, it seems to remove the on-demand instance from the ASG before shutting it down. As the lifecycle hooks are specified in the ASG, they are never triggered for those, which doesn't allow to rebalance the containers in the host before it gets shutdown.

With the little go skills I have, it seems that by default, the `terminateInstanceInAutoScalingGroup` method should be called : https://github.com/AutoSpotting/AutoSpotting/blob/master/core/autoscaling.go#L450

which would be perfectly fine, but it acts exactly as if `detachAndTerminateOnDemandInstance` was called instead.

I'm using terraform and the default module you provided (thanks !)  for my tests. I'm wondering if i have somehow misunderstood that the default termination policy calls the EC2 `DetachAndTerminate` api ?

I may have totally missed the docs about the termination method, here's how i use the terraform module: 

```module "autospotting" {
  source  = "cristim/autospotting/aws"
  version = "0.0.9"

  autospotting_regions_enabled              = "${var.aws_region}"
  autospotting_tag_filters                  = "Role=rancher_host,Environment=${var.platform_name}"

  autospotting_min_on_demand_number         = "0"
  lambda_run_frequency = "rate(1 minute)"
}```

**Comment by cristim** [comment]
Turns out you run an old version, the latest stable versions should work as expected using `terminateInstanceInAutoScalingGroup`. The Terraform module will need to be updated to the latest version.

**Comment by earzur** [comment]
ah ! that explains a lot ;-) thanks for the kind and helpful support.

**Comment by earzur** [comment]
```$ terragrunt -update
...
- module.autospotting
  Found version 0.0.9 of cristim/autospotting/aws on registry.terraform.io
  Updating source "cristim/autospotting/aws"
```

Does that mean i should not trust the terraform registy and run from github ?

**Comment by earzur** [comment]
i'll host my own repo for the module with an updated zip for the lambda, and sponsor as soon as i get it to run on our systems ;-)

**Comment by cristim** [comment]
Feel free to pick a recent build from https://cloudprowess.s3.amazonaws.com/index.html

I was told by user that the very last one is broken, but others should work fine.

**Comment by cristim** [comment]
For anyone brave enough to be a guinea pig for barely tested code, the latest build from the #354 branch should mitigate this issue for new ASGs.

To install it just click on this URL:
https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/create/template?stackName=AutoSpotting&templateURL=https://s3.amazonaws.com/cloudprowess/custom/template_build_1439509.yaml

Please report back if you notice any issues.

**Comment by cristim** [comment]
I've started working on this as part of #354.

So far my idea is to implement support for the launch lifecycle hooks of the unattached spot instances by handling the CloudTrail event that captures the failure to run the lifecycle hook action on the unattached spot instances(they fail with a validation error because the instances are not yet in the group). This would be handled like the other CloudWatch events and used it to trigger the Lambda function to attach the spot instance mentioned in the event as soon as this event was received.

Additionally it would need some reaping logic for the instances that failed to be set up and are running for longer than the lifecycle hook's abandon timeout.

Any thoughts on this?

**Comment by cristim** [comment]
The recently merged event-based execution mode should address this problem for most cases.

Closing this issue.
