### ISSUE TITLE
Feature: multiple lambda instances (with different configurations)

### ISSUE THREAD

**Issue by bfin** [AutoSpotting/AutoSpotting#315]
## Use case ##

Running multiple ASGs with different instance type requirements.

## Problem ##

In the terraform module (at least), several resource names are hard-coded (e.g., function name, role name, policy name) so the module cannot be easily used with multiple configurations.

## Proposal ##

Use variables so the module can be reused with different configurations.

**Comment by cristim** [comment]
Thanks for reporting this. 

I'm aware of this and I would love to see this as well but I am focusing on something else these days.

I've seen a number of forks addressed this issue but unfortunately their authors didn't try to get their work upstreamed yet.

Feel free to pick up one of those, file a PR about it and help getting it through if we need to do any changes.

**Comment by lenucksi** [comment]
Maybe it'd be an idea to list the forks addressing this here if you can instantly name them without searching a lot?

**Comment by bfin** [comment]
Currently testing a fork that addresses this. I'm curious: what is the reasoning behind the nested modules? The `terraform` directory contains a module, which references the module in the `autospotting` subdirectory, which in turn references the module in its own `lambda` subdirectory. Usually this structure would be used when each module is reused, but that doesn't seem to be the case here. And as a result, the same variables are defined multiple times. Would you mind explaining?

If the structure is the relic of some previous use case, I can restructure into a single, unified module and submit with the "labelling" PR.

**Comment by bfin** [comment]
An implication of the (current) nested module structure is that autospotting can currently be used in either of the 2 following ways:
```
module "autospotting" {
  source = "github.com/AutoSpotting/AutoSpotting//terraform/autospotting"
  ...
}
```
or by defining `asg_allowed_instance_types`, etc. instead of `autospotting_allowed_instance_types`, etc. (with the same values)
```
module "autospotting" {
  source = "github.com/AutoSpotting/AutoSpotting//terraform"
  ...
}
```
But I think this adds more confusion with no additional flexibility.

**Comment by cristim** [comment]
I'm not very familiar with the terraform code, but I doubt this nested module situation is intentional, maybe we just suck at writing proper/canonical Terraform modules.

Feel free to refractor it according to your proposal, I'm fine with that as long as the main module wouldn't require any changes for all existing users.

**Comment by xlr-8** [comment]
IINM the nested structure comes from https://github.com/AutoSpotting/AutoSpotting/pull/224#issuecomment-372130577 - which was odd to me, but sounded like the most adapted - or at least at that time.

Nested module shouldn't be an issue to instantiate multiple lambda, it might however require to make sure everything is uniquely identified with a param (suffix/prefix/env/whatever) to avoid collision.

The tag to flag ASG would most likely also require to be unique per module call.

**Comment by bfin** [comment]
Thanks for the background on the nested modules. And of course, you're right – it's a separate issue. The sub-submodule (`terraform/autospotting/lambda`) module is ok. After addressing the multiple instances here, I'll look into refactoring the `terraform` and `terraform/autospotting` modules.
