### ISSUE TITLE
Detach instance when spot termination notification is received (#309) - missing permission to invoke lambda

### ISSUE THREAD

**Issue by mello7tre** [AutoSpotting/AutoSpotting#319]
# Github issue #

## Issue type ##

- Bug Report
## Build number #

master

## Environment ##

- AWS region
- Type of environment: (VPC, EC2Classic or DefaultVPC)
- Anonymized launch configuration: 

```text
```

## Summary ##
The bug is about the new feature "Detach instance when spot termination notification is received ".

CloudFormation template "AutoSpotTerminationEvent" created by lambda TerminationEventRuleFunction is missing a permission to let sns topic "AutoSpotTerminationNotificationTopic" invoke main lambda AutoSpotting function "autospot-LambdaFunction".

Something like this shoud work:

        "LambdaPermissionAutoSpotTerminationNotificationTopic": {
            "Properties": {
                "Action": "lambda:InvokeFunction",
                "FunctionName": lambda_arn,
                "Principal": "sns.amazonaws.com",
                "SourceArn": {
                    "Ref": "AutoSpotTerminationNotificationTopic"
                }
            },
            "Type": "AWS::Lambda::Permission"
        }

## Steps to reproduce ##

Simply create cloudformation stack.

## Expected results ##

2 minutes before aws terminate a spot instance (as example for capacity-oversubscribed) an event rule ("AutoSpotTeminationEventRule") is triggered that publish a message to sns that invoke the main lambda.

## Actual results ##

Main lambda is not triggered and in CloudWatch metrics you can see failed invocations/notifications.
(you can simply manually publish any kind of message to sns queue),

**Comment by mello7tre** [comment]
We are missing topic policy too!
https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/CWE_Troubleshooting.html?shortFooter=true#NoMessagesPublishedSNS

Need to create a resource for it, something like (not tested it):

        "SNSTopicPolicyAutoSpotTeminationEventRule": {
            "Type": "AWS::SNS::TopicPolicy",
            "Properties": {
                "PolicyDocument": {
                    "Statement": [
                        {
                            "Action": "sns:Publish",
                            "Effect": "Allow",
                            "Principal": {
                                "Service": "events.amazonaws.com"
                            }
                        }
                    ],
                    "Version": "2012-10-17"
                },
                "Topics": [
                    {
                        "Ref": "AutoSpotTerminationNotificationTopic"
                    }
                ]
            }
        }

**Comment by cristim** [comment]
Thank you guys for reporting this, please create a PR with these changes.
