### ISSUE TITLE
Lifecycle Hook for ASG of ECS Cluster - Launched unused spot instance

### ISSUE THREAD

**Issue by mello7tre** [AutoSpotting/AutoSpotting#320]
# Github issue #

## Issue type ##

- Bug Report

## Build number #

master

## Environment ##

- AWS region
- Type of environment: (VPC, EC2Classic or DefaultVPC)
- Anonymized launch configuration: 

```text
```

## Summary ##

I have an ASG that power an ECS Cluster.
I created a lifecycle hook like the one in aws docs:
https://aws.amazon.com/blogs/compute/how-to-automate-container-instance-draining-in-amazon-ecs/

that simply begin draining terminating instances an wait until no task are running on an instance before signaling the hook.

I configured the ASG so that autospotting should replace the instance.
ASG is configured to have only one instance Desired=Min=Max=1 (it's a dev env),

Here the events:
1) Autospot (AS) launch a spot instance to replace the ondeman one
2) AS attach the new spot and terminate the ondemand one
3) Lifecycle Hook is triggered and begin draining the ondemand one, it take some time
4) AS still find the ondemand (have no way to know that is the one already replaced) and launch a new spot instance to replace it
5) No more task are runing on Ondemand, hook is signaled and instance finally terminate
6) AS examine ASG and see that all instances (the only one previous spot) are spot instances.
7) New spot instance of point 4 is leaved running.

Looking at code point 4 should no happen since:
func terminateInstanceInAutoScalingGroup consider only instances where State is == "running".

I attach a file with the relevant log sections, there you can see that is printed (datetime 2019/02/12 06:12:32)
[autospotting.log](https://github.com/AutoSpotting/AutoSpotting/files/2855640/autospotting.log)
:
"Found 1 on-demand instances running on a total of 2"

that string is printed by the above func.

I made some test and as soon as an instance is begin terminated his state go in "shutting-down".
So is a "mystery" why this happen....

## Steps to reproduce ##

Create an ASG that launch instances that should join an ecs cluster (even the default one).
Follow the instructions on:
https://aws.amazon.com/blogs/compute/how-to-automate-container-instance-draining-in-amazon-ecs/
to create a lambda triggered by a lifecycle hook on the ASG to begin draining and instance when terminating.
Launch an instance.
Launch some task on the cluster.
Configure autospot to replace ondemand on the ASG.
Wait and see what happen..

The triggering condition is that:
time to complete draining ondemand terminating instance should be greater than autospotting scheduled interval (default 5min) but lesser than (autospotting scheduled interval x 2) + ASG HealthGrace.

## Expected results ##

Autospotting should not leave running unused spot instances.

## Actual results ##

A spot instance not attached to an ASG is leaved running.

```text
```

**Comment by cristim** [comment]
@mello7tre Is this maybe already addressed in #325?

**Comment by mello7tre** [comment]
Yes i was just going to close it, you has been faster ;-)

**Comment by mello7tre** [comment]
Event described has not occurred anymore, and anyway now that #325 has been merged, even if it happen again, will resolve automatically.

**Comment by cristim** [comment]
great, thanks for the fix!
