### ISSUE TITLE
Terminate unused spot instances

### ISSUE THREAD

**Issue by mello7tre** [AutoSpotting/AutoSpotting#321]
# Github issue #

## Issue type ##

- Feature Idea

## Build number #

master

## Environment ##

- AWS region
- Type of environment: (VPC, EC2Classic or DefaultVPC)
- Anonymized launch configuration: 

```text
```

## Summary ##

(I have not tested it, but looking at code and using some logic behavior should be similar to the one described here)

It's partially related to the situation of issue #320 

Let's assume our ASG is configured for 3 desired min 2 max 4, and an autoscaling policy (tracking or step) is configured.

1) Autospot launch a spot instance
2) Before the next AutoSpot invocation, Autoscaling policy reduce the number of instances and terminate the ondemand one (the one that the next invocation of autospot should replace).
3) Autospot do not see more ondemand instance to replace and spot instance launched in point 1 remain active and unused.

i think the "logic" is in core/autoscaling.go func process lines 360:

        if !a.needReplaceOnDemandInstances() || !spotInstance.isReadyToAttach(a) {
                logger.Println("Waiting for next run while processing", a.name)
                return
        }

We should separate the or condition and process the two cases differently:
```
if !spotInstance.isReadyToAttach(a) {
    logger.Println("Waiting for next run while processing", a.name)
    return
}
if !a.needReplaceOnDemandInstances() {
    "here we shoud terminate the unused instance"
}
```

Maybe you already thought about it but there was some problems that currently i am missing...
In that case please le me know.

Regards, Alberto.

**Comment by cristim** [comment]
Thanks for reporting this issue, it's likely just an edge case we didn't run into yet.

Please try it out and create a PR with the proposed change once you get it work.

**Comment by cristim** [comment]
I've been thinking about it but I'm not sure if I understand what exactly is the problem with the current implementation. Can you elaborate a bit on this?

**Comment by mello7tre** [comment]
Currently when a spot instance is launched if AutoScalingGroup, before the next autospot execution (5 min default), for any reason (ScalingPolicy or scheduledaction or manually changes), terminate the ondemand instance that autospot next execution should have replaced, the launched spot instance, that is no more necessary, is not terminated.

One we launch a spot instance we assume that later it should be always attached to an ASG to replace an ondemand running one (that autospot "choose" before).
But this not always true.

**Comment by cristim** [comment]
I see now.

I agree with this patch, as long as it's not impacting the normal workflow for example by terminating a spot instance that was just launched and waiting for the grace period to pass before being swapped against an on demand instance.

**Comment by mello7tre** [comment]
If for that ASG, at the moment,  there is no need to replace an ondemand instance, there is no need to have a spot instance running (even if it still need to pass the grace period); we cannot know if we will need it in the future and after how much time, so it's better in my opinion to terminate it.

Considering this, i will even invert the condition order:
```
if !a.needReplaceOnDemandInstances() {
      logger.Println("Spot instance", spotInstanceID, "is not need anymore by ASG",
        a.name, "terminating the spot instance.")
      *spotInstance.terminate()
      return
}
if !spotInstance.isReadyToAttach(a) {
    logger.Println("Waiting for next run while processing", a.name)
    return
}
```

will try it in my env, and will try to simulate a condition where spot should be terminated.
If all goes well, and strange things do not happen, i will open a PR.
