### ISSUE TITLE
Terminating detached spot instance used to replace on demand one

### ISSUE THREAD

**Issue by mello7tre** [AutoSpotting/AutoSpotting#327]
# Github issue #

## Issue type ##

- Bug Report

## Build number #

master

## Environment ##

- AWS region
- Type of environment: (VPC, EC2Classic or DefaultVPC)
- Anonymized launch configuration: 

```text
```

## Summary ##

Following a spot termination notification, a previously launched spot instance has been detached from ASG, without decrementing ASG desired capacity so that ASG launch a new instance.

Happen that the new instance is launched in the same AZ that the spot terminating one.
Happen that before detached terminating spot instance terminate (so before 2 minutes), AutoSpotting is executed by scheduled event.

AutoSpotting (AS) look for spot instance ready do attach.
AS find the terminating spot instance:
it have the right tag "launched-for-asg" that match the ASG name and is state is still running.
AS find the ondeman one with the same AZ.
AS replace the ondemand instance with a nearly termination one!!!

AS and ASG log/events.
```
AS 2019-02-20T07:01:54.789Z 2019/02/20 07:01:54 Detached instance i-02a941d2d30a40a3c successfully
ASG At 2019-02-20T07:01:54Z instance i-02a941d2d30a40a3c was detached in response to a user request.
ASG At 2019-02-20T07:02:19Z Launching a new EC2 instance: i-095878a259a6c9e2b - an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 1.
AS 2019/02/20 07:02:32 autoscaling.go:442: rmq-a-d-AutoScalingGroup-1HSLJRZ51V8Q7 found on-demand instance i-095878a259a6c9e2b replacing with new spot instance i-02a941d2d30a40a3c
```

## Steps to reproduce ##

Create ASG with desired=min=max=1
Wait until AS replace the ondemand with a spot one.
One minute before next AS execution, pubblish the following message on sns spot termination notification Topic (replacing spot-instance-id with the right one):
```
{
  "detail": {
    "instance-id": "spot-instance-id",
    "instance-action": "terminate"
  }
}

```
Look for AS log and ASG events.
If the new ondemand instance is launched in the same AZ, the events previously described should happen. 

## Expected results ##

AutoSpotting should not use a terminating previously launched spot instance to replace an on demand one.

## Actual results ##

AutoSpotting have used a terminating previously launched spot instance to replace an on demand one.

## Possible Fix ##
I am working to add the option to choose between detaching or terminating a spot instance when a spot notification message is received.
Terminating it had the advantage of triggering lifecyclehook and to avoid this problem.
But if we want to keep detach as possible action we need to fix this.

One way should be to remove the tag "launched-for-asg" after attaching a spot instance successfully to an ASG.

**Comment by cristim** [comment]
I think the spot instance may still be outside of the group so the lifecycle hooks wouldn't run in this case.

What if we just delete the "launched-for-asg" tag when handling the spot instance termination notification regardless if the instance is in the group or not?

**Comment by mello7tre** [comment]
Yes we can delete the tag in spot_termination, before detaching or terminating it.

But i think that we have already all informations when we are attaching it, instead in spot_termination we must execute getAsgName, and if for any reason (temporary problem, timeout etc..) that func return error we are unable to delete it.

About terminating instead of detaching (controlled by parameter):
i have tested it and it work Lifehook is executed and, as his state change in "terminating", this bug is not triggered.
(i have already a version working but i am trying to add the cover/test)
