### ISSUE TITLE
AutoSpotting can cause client stack deletions to fail

### ISSUE THREAD

**Issue by iainelder** [AutoSpotting/AutoSpotting#332]
## Issue type ##

- Bug Report

## Build number #

```
961
```

## Configuration ##

Default settings

## Environment ##

- Region: us-west-2
- Type of environment: DefaultVPC
- Anonymized launch configuration: Not relevant

## Summary ##

AutoSpotting can cause the deletion of a client stack to fail.

A client stack is any whose ASG has the spot-enabled=true tag.

When a client stack is deleted, one of the security groups might fail to be deleted because it is a dependency of a recently-launched spot instance not yet attached to the group.

To fix it, the dependent spot instance needs to be deleted, and then the stack deletion needs to be repeated.

## Steps to reproduce ##

The "recently-launched" part is the key. To reproduce it, I think this has to happen:

* AutoSpotting launches a new spot instance
* You delete the stack before the instance's grace period has elapsed
* CloudFormation deletes the ASG, terminating all instances in the ASG, leaving intact the new spot instance
* CloudFormation deletes the security group for the instances in the ASG

## Expected results ##

That the client stack deletion terminates normally.

## Actual results ##

At the last step, the stack deletion should fail because the security group is still being used by new spot instance.

The CloudFormation event log will show an error like this:

```
19 Mar 2019 19:37:39	WebServerSecurityGroup	DELETE_FAILED	resource sg-037aadff951412345 has a dependent object (Service: AmazonEC2; Status Code: 400; Error Code: DependencyViolation; Request ID: 8fdc715e-9914-450d-81e7-9f80bc012345)
```

**Comment by iainelder** [comment]
This is a tricky edge case.

It is most likely to affect development and testing environments, where stacks are set up and torn down regularly.

As it theoretically affects all client stacks, it would be great to have a standard solution.

I don't see any obvious way to solve it on the AutoSpotting side.

Maybe it can be solved with some sort of pre-delete hook on the client side.

**Comment by cristim** [comment]
Maybe there is an event emitted when deleting Cloudformation stacks, which we can use to find such stale spot instances so we can terminate them.

We would find all the Autoscaling groups belonging to the terminating stack (they are tagged with the stack name) then we can get the unattached spot instances launched for this group and we can terminate all of them, maybe after removing all the security groups from them.

This would likely work but it assumes there's such an event emitted when deleting a Cloudformation stack.

**Comment by iainelder** [comment]
> Maybe there is an event emitted when deleting Cloudformation stacks

It appears so. The [create-stack](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html) and [update-stack](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/update-stack.html) commands have a `--notification-arns` parameter that allows you to specify a list of SNS topics that receive state change notifications.

@mbejda's blog article [Handling AWS Cloudformation Events](https://www.mbejda.com/handling-aws-cloudformation-events/) shows how to process these events.

It looks like it would require a topic and a lambda function in the same region as the CloudFormation stack.

It would require each client stack to create or update their stacks with the name of AutoSpotting's SNS topic.

In our case, the important event would probably be the one whose message shows a DELETE_IN_PROGRESS state on the main stack resource itself.

Triggering on the initial stack deletion should give AutoSpotting time to remove the security groups from the unattached spot instances before CloudFormation tries to delete them.

**Comment by cristim** [comment]
Yes, I've seen that article and looks promising.

I'm working to anyway add a regional lightweight Lambda function and we already have Cloudformation stacks in each of the regions. 

We just need to extend them a bit with the regional SNS topic and to make sure the Lambda functions update all the existing stacks to send notifications to the regional topics. 

This is a bit of work but it's definitely doable. The question is whether it worth adding this additional complexity for this relatively isolated edge case. What do you think?

**Comment by iainelder** [comment]
It's not a high priority for my team. We can work around it manually when we delete stacks by terminating the unattached spot instance, if it exists.

Now that it's documented here, others affected by the problem can refer to this ticket.

If enough users are bothered by it, we could implement the fix you describe.

**Comment by cristim** [comment]
Alternatively we can also terminate all spot instances launched for a given group if the group is no longer available

**Comment by iainelder** [comment]
> Alternatively we can also terminate all spot instances launched for a given group if the group is no longer available

That sounds like a good thing to do anyway, as a safeguard against orphaned instances.

**Comment by kapilt** [comment]
Rather than watching cfn stacks, why not track cwe trail for delete asg, and cleanup on in progress activities for the named asg. Ie this issue isn’t per se cfn specific.

**Comment by cristim** [comment]
That's a great idea, thanks!

We already have the infrastructure in place to listen for these events, we just need to create an event rule and a handling logic

**Comment by cristim** [comment]
Addressing this is the next thing on my agenda, I expect it to be fixed within the next few weeks.

In the meantime, as a workaround to avoid this from happening again, right before the deletion of the CloudFormation stack you can run the AutoSpotting Docker container from the CLI to delete any unattached spot instances for the current group:

`docker -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY run autospotting  --cron_schedule_state off --tag_filters aws:cloudformation:stack-id=$CFN_STACK_ARN`

**Comment by cristim** [comment]
For anyone brave enough to be a guinea pig for barely tested code, the latest build from the #354 branch should mitigate this issue for new ASGs.

To install is just click on this URL:
https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/create/template?stackName=AutoSpotting&templateURL=https://s3.amazonaws.com/cloudprowess/custom/template_build_1439509.yaml

**Comment by cristim** [comment]
The recently merged event-based execution mode should address this problem for most cases.

Closing this issue.
