### ISSUE TITLE
Launches extra instance after all replacements, orphans it

### ISSUE THREAD

**Issue by iainelder** [AutoSpotting/AutoSpotting#335]
# Github issue #

## Issue type ##

- Bug Report

## Build number #

```text
961
```

## Configuration ##

Launched with default settings.

Execution frequency of 1 minute.

Command line flags from CloudWatch Logs:

```
2019/03/27 14:58:37 Parsed command line flags: regions='us-west-2' min_on_demand_number=0 min_on_demand_percentage=0.0 allowed_instance_types= disallowed_instance_types= on_demand_price_multiplier=1.00 spot_price_buffer_percentage=10.000 bidding_policy=normal tag_filters=spot-enabled=true tag_filter_mode=opt-in spot_product_description=Linux/UNIX (Amazon VPC) instance_termination_method=autoscaling
```

## Environment ##

- AWS region: us-west-2
- Type of environment: DefaultVPC
- Anonymized launch configuration: Not relevant

## Summary ##

AutoSpotting launches one more instance than necessary after replacing all the on-demand instances. Before the extra instance passes grace period, it is orphaned by AutoSpotting, disappearing from the logs. The unattached instance keeps running indefinitely.

## Steps to reproduce ##

Launch a client stack with and ASG with minimum capacity 2 and maximum capacity 3.

Wait until all the on-demand instances are replaced.

Examine the logs.

## Expected results ##

There are two spot instances in the ASG, and no extra unattached spot instances.

## Actual results ##

There are two spot instances in the ASG and one extra unattached spot instance.

The AutoSpotting log shows that an extra spot instance is launched, and then orphaned before it passes grace period.

The ASG's scaling activity shows scaling events that correspond with AutoSpotting's logged actions.

### Scaling activity log

```json
[
  {
    "StartTime": "2019-03-27T15:33:18.165Z",
    "EndTime": "2019-03-27T15:33:51Z",
    "Cause": "At 2019-03-27T15:33:12Z a user request update of AutoScalingGroup constraints to min: 2, max: 3, desired: 2 changing the desired capacity from 0 to 2.  At 2019-03-27T15:33:15Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 2."
  },
  {
    "StartTime": "2019-03-27T15:33:18.372Z",
    "EndTime": "2019-03-27T15:33:52Z",
    "Cause": "At 2019-03-27T15:33:12Z a user request update of AutoScalingGroup constraints to min: 2, max: 3, desired: 2 changing the desired capacity from 0 to 2.  At 2019-03-27T15:33:15Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 2."
  },
  {
    "StartTime": "2019-03-27T15:39:39.218Z",
    "EndTime": "2019-03-27T15:39:44Z",
    "Cause": "At 2019-03-27T15:39:39Z an instance was added in response to user request. Keeping the capacity at the new 1."
  },
  {
    "StartTime": "2019-03-27T15:39:39.504Z",
    "EndTime": "2019-03-27T15:45:38Z",
    "Cause": "At 2019-03-27T15:39:39Z instance i-0a1afbf60792c1234 was taken out of service in response to a user request, shrinking the capacity from 3 to 2."
  },
  {
    "StartTime": "2019-03-27T15:46:38.908Z",
    "EndTime": "2019-03-27T15:47:11Z",
    "Cause": "At 2019-03-27T15:46:38Z an instance was added in response to user request. Keeping the capacity at the new 1."
  },
  {
    "StartTime": "2019-03-27T15:46:39.131Z",
    "EndTime": "2019-03-27T15:52:37Z",
    "Cause": "At 2019-03-27T15:46:39Z instance i-04f10393ef5481234 was taken out of service in response to a user request, shrinking the capacity from 3 to 2."
  }
]
```

Captured using [aws-cli](https://aws.amazon.com/es/cli/) and [jq](https://stedolan.github.io/jq/) like this:

```bash
aws autoscaling describe-scaling-activities \
--auto-scaling-group-name ExampleGroup \
--profile spotlight-dev \
--region us-west-2 \
> ~/tmp/scaling-log

cat ~/tmp/scaling-log |
jq '.Activities|sort_by(.StartTime)|map({StartTime,EndTime,Cause})' \
> ~/tmp/scaling-log-copy
```

### AutoSpotting log

Spot instance 1 launched normally at 15:33.

```text
2019/03/27 15:33:37 autoscaling.go:374: Adding instances to ExampleGroup
2019/03/27 15:33:37 autoscaling.go:330: Finding spot instances created for ExampleGroup
2019/03/27 15:33:37 autoscaling.go:335: No spot instances were found for  ExampleGroup
2019/03/27 15:33:38 autoscaling.go:686: ExampleGroup Counting already running on demand instances 
2019/03/27 15:33:38 autoscaling.go:702: ExampleGroup Found 2 on-demand instances running on a total of 2
2019/03/27 15:33:38 autoscaling.go:291: Currently more than enough OnDemand instances running
2019/03/27 15:33:39 instance.go:345: ExampleGroup Created spot instance i-0615af589112b1234
```

Spot instance 1 passes grace period and replaces an on demand instance at 15:39.

```text
2019/03/27 15:39:38 autoscaling.go:374: Adding instances to ExampleGroup
2019/03/27 15:39:38 autoscaling.go:330: Finding spot instances created for ExampleGroup
2019/03/27 15:39:38 autoscaling.go:686: ExampleGroup Counting already running on demand instances 
2019/03/27 15:39:38 autoscaling.go:702: ExampleGroup Found 2 on-demand instances running on a total of 2
2019/03/27 15:39:38 autoscaling.go:291: Currently more than enough OnDemand instances running
2019/03/27 15:39:38 instance.go:519: Considering  i-0615af589112b1234 for attaching to ExampleGroup
2019/03/27 15:39:38 instance.go:525: Instance uptime: 5m59s
2019/03/27 15:39:38 instance.go:531: The spot instance i-0615af589112b1234  has passed grace period and is ready to attach to the group.
2019/03/27 15:39:38 autoscaling.go:365: us-west-2 Found spot instance: i-0615af589112b1234 Attaching it to ExampleGroup
2019/03/27 15:39:38 autoscaling.go:416: ExampleGroup Retrieving instance details for  i-0615af589112b1234
2019/03/27 15:39:38 autoscaling.go:423: ExampleGroup i-0615af589112b1234 is in the availability zone us-west-2c looking for an on-demand instance there
2019/03/27 15:39:38 autoscaling.go:435: ExampleGroup found on-demand instance i-0a1afbf60792c1234 replacing with new spot instance i-0615af589112b1234
2019/03/27 15:39:39 autoscaling.go:657: us-west-2 ExampleGroup Terminating instance: i-0a1afbf60792c1234
```

Spot instance 2 launched normally at 15:40.

```text
2019/03/27 15:40:38 autoscaling.go:374: Adding instances to ExampleGroup
2019/03/27 15:40:38 autoscaling.go:330: Finding spot instances created for ExampleGroup
2019/03/27 15:40:38 autoscaling.go:335: No spot instances were found for  ExampleGroup
2019/03/27 15:40:38 autoscaling.go:686: ExampleGroup Counting already running on demand instances 
2019/03/27 15:40:38 autoscaling.go:702: ExampleGroup Found 2 on-demand instances running on a total of 3
2019/03/27 15:40:38 autoscaling.go:291: Currently more than enough OnDemand instances running
2019/03/27 15:40:39 instance.go:345: ExampleGroup Created spot instance i-044c89ca0577f1234
```

Spot instance 2 passes grace period and replaces on-demand instance at 15:46.

```text
2019/03/27 15:46:38 autoscaling.go:374: Adding instances to ExampleGroup
2019/03/27 15:46:38 autoscaling.go:330: Finding spot instances created for ExampleGroup
2019/03/27 15:46:38 autoscaling.go:686: ExampleGroup Counting already running on demand instances 
2019/03/27 15:46:38 autoscaling.go:702: ExampleGroup Found 1 on-demand instances running on a total of 2
2019/03/27 15:46:38 autoscaling.go:291: Currently more than enough OnDemand instances running
2019/03/27 15:46:38 instance.go:519: Considering  i-044c89ca0577f1234 for attaching to ExampleGroup
2019/03/27 15:46:38 instance.go:525: Instance uptime: 5m59s
2019/03/27 15:46:38 instance.go:531: The spot instance i-044c89ca0577f1234  has passed grace period and is ready to attach to the group.
2019/03/27 15:46:38 autoscaling.go:365: us-west-2 Found spot instance: i-044c89ca0577f1234 Attaching it to ExampleGroup
2019/03/27 15:46:38 autoscaling.go:416: ExampleGroup Retrieving instance details for  i-044c89ca0577f1234
2019/03/27 15:46:38 autoscaling.go:423: ExampleGroup i-044c89ca0577f1234 is in the availability zone us-west-2b looking for an on-demand instance there
2019/03/27 15:46:38 autoscaling.go:435: ExampleGroup found on-demand instance i-04f10393ef5481234 replacing with new spot instance i-044c89ca0577f1234
2019/03/27 15:46:38 autoscaling.go:657: us-west-2 ExampleGroup Terminating instance: i-04f10393ef5481234
```

Spot instance 3 launched at 15:47. This is not normal!

AutoSpotting believes that there is still 1 on-demand instance running.

```text
2019/03/27 15:47:37 region.go:338: Enabling group ExampleGroup for processing because its tags, the currently configured  filtering mode (opt-in) and tag filters are aligned
2019/03/27 15:47:38 autoscaling.go:374: Adding instances to ExampleGroup
2019/03/27 15:47:38 autoscaling.go:330: Finding spot instances created for ExampleGroup
2019/03/27 15:47:38 autoscaling.go:335: No spot instances were found for  ExampleGroup
2019/03/27 15:47:38 autoscaling.go:686: ExampleGroup Counting already running on demand instances 
2019/03/27 15:47:38 autoscaling.go:702: ExampleGroup Found 1 on-demand instances running on a total of 3
2019/03/27 15:47:38 autoscaling.go:291: Currently more than enough OnDemand instances running
2019/03/27 15:47:39 instance.go:345: ExampleGroup Created spot instance i-0c78d0f7876c01234
```

Spot instance 3 waits for the grace period to elapse for a few minutes, until 15:51.

```text
2019/03/27 15:51:37 region.go:338: Enabling group ExampleGroup for processing because its tags, the currently configured  filtering mode (opt-in) and tag filters are aligned
2019/03/27 15:51:38 autoscaling.go:374: Adding instances to ExampleGroup
2019/03/27 15:51:38 autoscaling.go:253: No default value for on-demand instances specified, skipping.
2019/03/27 15:51:38 autoscaling.go:330: Finding spot instances created for ExampleGroup
2019/03/27 15:51:38 autoscaling.go:686: ExampleGroup Counting already running on demand instances 
2019/03/27 15:51:38 autoscaling.go:702: ExampleGroup Found 1 on-demand instances running on a total of 3
2019/03/27 15:51:38 autoscaling.go:291: Currently more than enough OnDemand instances running
2019/03/27 15:51:38 instance.go:519: Considering  i-0c78d0f7876c01234 for attaching to ExampleGroup
2019/03/27 15:51:38 instance.go:525: Instance uptime: 3m59s
2019/03/27 15:51:38 instance.go:536: The spot instance i-0c78d0f7876c01234 is still in the grace period, waiting for it to be ready before we can attach it to the group...
2019/03/27 15:51:38 autoscaling.go:361: Waiting for next run while processing ExampleGroup
```

Spot instance 3 disappears from the log as of 15:52.

AutoSpotting sees that there are no on-demand instances running, and forgets about the instance.

```text
2019/03/27 15:52:37 region.go:338: Enabling group ExampleGroup for processing because its tags, the currently configured  filtering mode (opt-in) and tag filters are aligned
2019/03/27 15:52:38 autoscaling.go:374: Adding instances to ExampleGroup
2019/03/27 15:52:38 autoscaling.go:253: No default value for on-demand instances specified, skipping.
2019/03/27 15:52:38 autoscaling.go:330: Finding spot instances created for ExampleGroup
2019/03/27 15:52:38 autoscaling.go:686: ExampleGroup Counting already running on demand instances 
2019/03/27 15:52:38 autoscaling.go:702: ExampleGroup Found 0 on-demand instances running on a total of 2
2019/03/27 15:52:38 autoscaling.go:295: Currently OnDemand running equals to the required number, skipping run
2019/03/27 15:52:38 autoscaling.go:361: Waiting for next run while processing ExampleGroup
```

Captured using [saw](https://github.com/TylerBrock/saw) with a command like this:

```bash
saw get /aws/lambda/AutoSpotting-LambdaFunction-CU9KBY7TCUNM \
--start -2h \
--profile spotlight-dev \
--region us-west-2 \
> ~/autospotting-log
```

**Comment by iainelder** [comment]
Could this have something to do with the load balancer's connection draining?

We are using application load balancers (ALBs). They have a default [connection draining time](
https://docs.aws.amazon.com/es_es/elasticloadbalancing/latest/APIReference/API_TargetGroupAttribute.html) of 300 seconds.

> `deregistration_delay.timeout_seconds` - The amount of time, in seconds, for Elastic Load Balancing to wait before changing the state of a deregistering target from `draining` to `unused`. The range is 0-3600 seconds. The default value is 300 seconds. If the target is a Lambda function, this attribute is not supported.

Could the delayed termination of the instance by why AutoSpotting decides to launch an extra instance?

In any case, why doesn't AutoSpotting clean up the extra instance later?

**Comment by cristim** [comment]
I also suspect the load balancer draining, and as a workaround I would recommend to set the execution frequency longer than the draining period.

I agree that we should terminate the orphaned instance, just like we also discussed in the other issue about the stack deletion spot orphans.

**Comment by lenucksi** [comment]
The other issue would then likely be #332.

**Comment by iainelder** [comment]
> I also suspect the load balancer draining, and as a workaround I would recommend to set the execution frequency longer than the draining period.

We will try the workaround. It seems like the smallest safe execution frequency would be 6 minutes.

Would it make sense for AutoSpotting to detect connection draining? I think you can detect it using the [`aws elbv2 describe-target-health`](https://docs.aws.amazon.com/cli/latest/reference/elbv2/describe-target-health.html) API, although I haven't tried it.

**Comment by cristim** [comment]
Increasing the frequency shouldn't make much difference, this is only noticeable you have very large groups. For long running instances you would maybe waste a few minutes of on-demand time, which is negligible if you run instances for days or weeks.

Regarding the connection draining handling, we could with not so much effort skip on-demand instances that are currently being drained.

The LoadBalancer is configured at the AutoScaling group level, we can just query its instances and check the status of the instances we would like to replace and skip it if it's being drained. I think the ALB complicates the logic a bit because of the target group, and we also may need to have a different logic for the NLB.

Alternatively, hopefully the draining instance would also have a certain flag set on the list of the AutoScaling group instances, that would simplify the logic since we wouldn't need to query the various types of load balancers independently. But this may be unlikely and needs to be investigated.

**Comment by cristim** [comment]
@iainelder are you still having issues with this, or did you get it work?

Please reopen if you are still struggling with this.

**Comment by gamefundas** [comment]
@cristim I noticed this happening in my VPC. Duplicate (both normal and spot) instances running together. Had to eliminate one of them manually. This happened even for cases where AS was configured to run only one node.

**Comment by cristim** [comment]
The duplication is normal during the grace period of the spot instances, we have seen cases of stale spot instances after scaling în but it should be handled by the current implementation. 

Other cases may be for deleted ASGS, but for those we don't have cleaning logic in the current implementation. Patches for this would be very welcome.
