### ISSUE TITLE
LaunchTemplate: InvalidParameterCombination Error

### ISSUE THREAD

**Issue by TheFynx** [AutoSpotting/AutoSpotting#345]
# Github issue #

Originally mentioned here: https://github.com/AutoSpotting/AutoSpotting/issues/285#issuecomment-498236986
But individual was directed to open a Github Issue, did not see one. 

## Issue type ##
- Bug Report

## Build number #

```text
5ada676d051e420530b4633ef21540464bd6f113
```

## Configuration ##

Settings passed to Lambda Environment
```hcl
  autospotting_allowed_instance_types       = "m5.large, m5d.large"
  autospotting_bidding_policy               = "normal"
  autospotting_min_on_demand_percentage     = "50"
  autospotting_regions_enabled              = "us-east-1"
  autospotting_spot_price_buffer_percentage = "10"
  autospotting_spot_product_description     = "Linux/UNIX (Amazon VPC)"
  autospotting_tag_filters                  = "spot-enabled=true"
```

## Environment ##

- AWS region: us-east-1
- Type of environment: VPC
- Anonymized launch configuration: Using Launch Template from custom TF Module, will have to pull copy and anonymize if needed

## Summary ##

Running into an issue using Launch Templates, had been waiting on the merge of https://github.com/AutoSpotting/AutoSpotting/pull/303 to utilize AutoSpotting as we're utilizing Launch Template for everything.

I'm assuming the issue has to do with LaunchTemplates as it did not affect testing without Templates.

Log Output:

```
2019/06/04 19:57:38 instance.go:452: BiddingPolicy: normal
2019/06/04 19:57:38 instance.go:455: Bidding base on demand price 0.096
2019/06/04 19:57:38 instance.go:422: us-east-1b cluster-name Launching spot instance of type m5.large with bid price 0.096
2019/06/04 19:57:38 instance.go:423: us-east-1b cluster-name
2019/06/04 19:57:38 instance.go:430: Couldn't launch spot instance: InvalidParameterCombination: Network interfaces and an instance-level subnet ID may not be specified on the same request
```

## Steps to reproduce ##

- Launch Autoscale Group using on-demand instances and launch template for configuration with Tags to enable autospotting.

## Expected results ##

Expected Autoscale Group to have 50% of instances swapped from On-Demand to Spot Instances

## Actual results ##

```text
2019/06/04 19:57:38 instance.go:430: Couldn't launch spot instance: InvalidParameterCombination: Network interfaces and an instance-level subnet ID may not be specified on the same request
```

**Comment by cristim** [comment]
Thanks for reporting this issue.

Please post the anonymized details of the launch configuration, launch template and also the output of the describe instances command against one of the on demand instances that fail to be replaced.

**Comment by cristim** [comment]
Please have a look at the proposal I mentioned in #346, may work for this as well.

**Comment by cristim** [comment]
@TheFynx please provide the required information in order for me to be able to reproduce this and hopefully come up with a fix.

**Comment by cristim** [comment]
@TheFynx please test the code I submitted in #352, it should address your issue.
