### ISSUE TITLE
Fails to connect to aws autoscaling service - No host error

### ISSUE THREAD

**Issue by gamefundas** [AutoSpotting/AutoSpotting#349]
I am getting the following error when the lamda runs

Post https://autoscaling.us-east-1.amazonaws.com/: proxyconnect tcp: dial tcp: lookup proxy on 169.254.169.253:53: no such host

could this be a proxy configuration issue?

I have set the following environment variables for lambda

HTTP_PROXY=http://myproxy:port
HTTPS_PROXY=https://myproxy:port
NO_PROXY=169.254.169.254

Am I missing something. Does golang use the proxy configuration from environment variables at runtime?

**Comment by cristim** [comment]
Try to run the Lambda outside your own VPC and unset those variables

**Comment by gamefundas** [comment]
Thanks @cristim 

I managed to get it running by adding the Route53 DNS IP also to the no_proxy list. It seems to be working now.

**Comment by cristim** [comment]
Great to hear, but I haven't seen anyone else need to do this. Do you have any particular setup?

**Comment by gamefundas** [comment]
I was trying to run this within my VPC and hence had to make sure that I have the right proxy configuration for Lambda to communicate with AWS service url's.

**Comment by cristim** [comment]
O never tried to run it within a VPC, I guess it should work if you have outbound network connectivity from the VPC using a NAT gateway or IGW
