### ISSUE TITLE
Spot Instance Termination is Generic

### ISSUE THREAD

**Issue by cfarrend** [AutoSpotting/AutoSpotting#362]
# Github issue #

## Issue type ##
- Bug Report

## Build number #

master branch

## Summary ##

During Spot Instance termination, the function does not take into consideration the tags of the instance's AutoScaling group or will run into a conflict if multiple AutoSpotting functions are deployed. 

AutoScaling groups that do not use AutoSpotting are also affected, this can cause issues with tools such as https://github.com/pusher/k8s-spot-termination-handler

## Steps to reproduce ##
Trigger spot termination event

## Expected results ##
Spot termination event to only affect a subset of instances - those that are covered by AutoSpotting and have the correct tags

## Actual results ##
Any instance that has spot termination is affected

**Comment by cristim** [comment]
Thanks for reporting this issue.

I currently don't have bandwidth to look into this but I'd really appreciate a contribution on top of the branch I'm working on for #354

**Comment by cfarrend** [comment]
Hey @cristim I have raised PR #363 with the code I've been working with so far, any feedback is appreciated

**Comment by gabegorelick** [comment]
This seems to be a huge blocker in running AutoSpotting in multi-tenant environments.
