### ISSUE TITLE
Evicting/Taint Nodes

### ISSUE THREAD

**Issue by mzupan** [AutoSpotting/AutoSpotting#364]
It seems to me autospotting is terminating the node from the ASG and buying a spot instance. Is there a way to have autospotting taint and drain the node first before killing it? I have work loads that don't like to be randomly killed.

**Comment by cristim** [comment]
Thanks for your question.

You would have the same problem if instances are terminated for any other reason, it just happens that AutoSpotting does it more often than usual so it becomes noticeable.

If this is causing problems try using the Termination lifecycle hooks on your Autoscaling group. AutoSpotting should support those.

Please feel free to reach out again if this doesn't work.
