### ISSUE TITLE
Multiple autospotting lambda functions on single ASG?

### ISSUE THREAD

**Issue by vdoodala** [AutoSpotting/AutoSpotting#365]
# Github issue #

## Issue type ##

- Question ?

## Environment ##

- AWS region - (us-west-2)
- Type of environment: (VPC)

## Summary ##

I would like to know if we run multiple autospotting lambda functions on single ASG ? will there be any race-around condition in replacing on-demand instances ?

**Comment by cristim** [comment]
It depends on the timing of the cron events, if you run them at the same time you will likely run into race conditions.

If you can get them to run even a few seconds apart, they should work fine.

I'm curious about why you would run more of them. Can you explain your use case?

**Comment by vdoodala** [comment]
We are running a cluster of more than 250 nodes, so its taking too much time for autospotting to replace on-demand instances. So, may be if we run multiple autospotting lambda functions, we can solve this problem ?

**Comment by cristim** [comment]
I doubt it helps with this use case but by all means try it and see if it actually works.

The event based mode I'm working on at #354 is likely to support this once I'm done with it. 

It's a significant architectural change, lot of new code and still work in progress, barely tested and likely still buggy but feel free to give it a try and let me know if you notice any issues.

**Comment by cristim** [comment]
Closing this

@vdoodala  feel free to re-open if you have further questions on this topic
