### ISSUE TITLE
Increasing autospotting_min_on_demand_number does not cause replacement of existing spot instances

### ISSUE THREAD

**Issue by gabegorelick** [AutoSpotting/AutoSpotting#375]
## Issue type ##

Bug Report

## Build number #

Custom build of 9b438dc with no diff.

## Configuration ##

None

## Environment ##

- AWS region: us-east-1
- Type of environment: VPC

## Summary ##

Increasing the `autospotting_min_on_demand_number` tag on an ASG does not cause AutoSpotting to replace existing spot instances with on-demand instances.

## Steps to reproduce ##

1. Launch an ASG of size 2.
2. Set up AutoSpotting so that both instances in ASG are replaced with spot
3. Set `autospotting_min_on_demand_number` to `1`

## Expected results ##

AutoSpotting should launch an on-demand instance and terminate a spot instance.

## Actual results ##

AutoSpotting sees the tag change, as evidenced by this log:

> autoscaling_configuration.go:152: Loaded MinOnDemand value to 1 from tag autospotting_min_on_demand_number 

But AutoSpotting does not convert any spot instances to on-demand.

**Comment by gabegorelick** [comment]
I don't see any code related to replacing spot instances with on-demand in https://github.com/AutoSpotting/AutoSpotting/blob/master/core/autoscaling.go, so I guess AutoSpotting doesn't support this? 

I would expect this to work similar to a mixed instance ASG where you can adjust your on-demand %/fixed number and the number of active spot instances is automatically updated.

**Comment by cristim** [comment]
The way it's supposed to work is by terminating a spot instance and allowing the group to launch an on demand replacement instance.

Considering your experiment with reducing the IAM permissions mentioned recently on another issue, did you by any chance remove the permissions to terminate your on-demand instance?

**Comment by gabegorelick** [comment]
> The way it's supposed to work is by terminating a spot instance and allowing the group to launch an on demand replacement instance.

@cristim Are you saying AutoSpotting is supposed to terminate the spot instance, or the ASG is supposed to terminate it?

**Comment by cristim** [comment]
Autospotting would terminate the spot instance

**Comment by gabegorelick** [comment]
@cristim I don't see any errors in my logs. After it finds the min on demand tag it says there's no work to do.

Where does AutoSpotting attempt to terminate the spot instance? If I know where it happens in the codebase I can potentially investigate more.

**Comment by cristim** [comment]
Sorry, but as you don't currently have a support plan I can't support you any further.

You have full access to the source code, feel free to use it.

**Comment by gabegorelick** [comment]
I see where AutoSpotting handles this now. Relevant code is https://github.com/AutoSpotting/AutoSpotting/blob/972bc61ac8c3315bdbb30245057b24ab74baa17a/core/autoscaling.go#L58.

It seems to be working now. I think I was running into https://github.com/AutoSpotting/AutoSpotting/blob/972bc61ac8c3315bdbb30245057b24ab74baa17a/core/autoscaling.go#L73.

Apologies for the noise. Thanks for everything you do @cristim!
