### ISSUE TITLE
spot_price_buffer_percentage=0 is ignored

### ISSUE THREAD

**Issue by gabegorelick** [AutoSpotting/AutoSpotting#380]
## Issue type ##

Bug Report

## Build number #

master

## Summary ##

If `spot_price_buffer_percentage` is 0, the default of 10 is used. 

https://github.com/AutoSpotting/AutoSpotting/blob/9b438dc47cbfd9587b042d5b2aaac2765c28a4e0/core/autoscaling_configuration.go#L138-L141

But a value of 0 is useful to bid at the current spot price. 

My specific use case involves testing spot instance interruption. Bidding at the current spot price maximizes the chances of the instance being interrupted when the price rises, while still ensuring that we're able to allocate the instance in the first place. I can work around this by using a sufficiently small value of `spot_price_buffer_percentage`, but that's messier.

## Steps to reproduce ##

Set `spot_price_buffer_percentage=0` and bidding policy to `aggressive`.

## Expected results ##

Bid at current spot price.

## Actual results ##

Bid at 10% over spot price.

**Comment by cristim** [comment]
Thanks for all your contributions, I really appreciate your work.

Unfortunately I don't have time to look at it this weekend but I will have a look sometime next week.
