### ISSUE TITLE
nil pointer dereference when processing spot termination event for instance not in an ASG

### ISSUE THREAD

**Issue by gabegorelick** [AutoSpotting/AutoSpotting#387]
# Github issue #

## Issue type ##

Bug Report

## Build number #

master

## Summary ##

When AutoSpotting receives a CloudWatch event signaling that a spot instance will be terminated, it calls `getAsgName`:
https://github.com/AutoSpotting/AutoSpotting/blob/9b438dc47cbfd9587b042d5b2aaac2765c28a4e0/core/spot_termination.go#L118-L131

`*result.AutoScalingInstances[0].AutoScalingGroupName` will segfault if  `AutoScalingInstances` is empty, which I think will be the case if the instance does not belong to an ASG. This can theoretically happen if the instance in question was a spot instance not managed by AutoSpotting.

## Steps to reproduce ##

I haven't tested this in AWS, but here's a unit test that simulates it:

```go
func TestIsInAutoSpottingASG(t *testing.T) {
	instanceID := "dummyInstanceID"

	tests := []struct {
		name             string
		spotTermination  *SpotTermination
		tagFilteringMode string
		filterByTags     string
		expected         bool
	}{
		{
			name: "When instance is not in an ASG",
			spotTermination: &SpotTermination{
				asSvc: mockASG{
					dasio: &autoscaling.DescribeAutoScalingInstancesOutput{
						AutoScalingInstances: []*autoscaling.InstanceDetails{},
					},
				},
			},
			tagFilteringMode: "opt-in",
			filterByTags:     "",
			expected:         false,
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {

			actual := tc.spotTermination.isInAutoSpottingASG(&instanceID, tc.tagFilteringMode, tc.filterByTags)

			if tc.expected != actual {
				t.Errorf("isInAutoSpottingASG received for %s: %v expected %v", tc.name, actual, tc.expected)
			}
		})
	}
}
```

## Expected results ##

AutoSpotting ignores instances that do not belong to an autoscaling group.

## Actual results ##

Segfault

**Comment by gabegorelick** [comment]
I have a fix for this in my working branch of https://github.com/AutoSpotting/AutoSpotting/pull/363. I can break it out if desired.

**Comment by cristim** [comment]
Thanks, that would be great
