### ISSUE TITLE
Tag spot requests

### ISSUE THREAD

**Issue by gabegorelick** [AutoSpotting/AutoSpotting#410]
# Github issue #

## Issue type ##

- Feature Idea

## Summary ##

AutoSpotting tags the spot _instances_ it launches, but it does not tag the spot _requests_:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-requests.html#concepts-spot-instances-request-tags

Tagging the spot requests can be useful to, for example, group spot requests by ASG or some other value. 

Spot requests also support a `Name` tag that's given its own column in the Spot Requests UI. Perhaps AutoSpotting should generate a name tag if none is provided, e.g. `$ASG_NAME autospotting instance`. 

Tags that I think are worthwhile for AutoSpotting to add automatically, in addition to any tags specified by the user:
- Name
- `launched-for-asg`
- `launched-by-autospotting` (to differentiate AutoSpotting spot requests from others)

## Steps to reproduce ##

1. Navigate to Spot Requests section of AWS Console
2. Try to query for all spot requests for a given ASG

## Expected results ##

You can query all spot requests for a given ASG

## Actual results ##

You cannot query this way

**Comment by cristim** [comment]
We're no longer creating the spot requests, like we used to do for a while. We're now using the RunInstances EC2 API call, which will take care of the spot instance requests under the hood.

I'm not sure if this API call allows us to tag the spot instance requests that it maintains.

I think we could do the tagging ourselves but I am reluctant to add this logic and increase the complexity with very little benefits.

**Comment by gabegorelick** [comment]
> I'm not sure if this API call allows us to tag the spot instance requests that it maintains.

It does not. You have to tag them manually after the spot request is created. I think we can potentially do this when attaching the spot instance to the ASG. 

> I think we could do the tagging ourselves but I am reluctant to add this logic and increase the complexity with very little benefits.

I may agree with you, but let's see what the code looks like first :)

**Comment by cristim** [comment]
@gabegorelick I'm going to close this, as I have bigger fish to fry.

Feel free to reopen it if you're still interested in this functionality enough to also contribute a pull request for it.
