### ISSUE TITLE
Maintainers/contributors wanted

### ISSUE THREAD

**Issue by cristim** [AutoSpotting/AutoSpotting#431]
**Later edit**
My situation changed after the lockdowns relaxed in my area and for now I'm back to working on AutoSpotting a few hours a week.

If you aren't happy with the pace of development and would like to see more progress, please support me on [Github Sponsors](https://github.com/sponsors/cristim), this would make a huge difference. 

Also please +1 the issues you care about most, I use these votes to prioritise my future work.

**Initial version**
As you probably saw at the top of the readme, I'm no longer in a position to maintain/contribute meaningfully to the development/maintenance effort and looking for someone to take over at least for the remainder of the current situation.

If you're an existing contributor interested to take over maintainership or even just to contribute more code, feel free to comment below.

**Comment by uguracar** [comment]
Hi Cristian, thanks for your all valuable efforts. If there are no volunteers, we are considering to take over the development/maintainership as MaxSpotter team. What do you think? Thanks. 
Ugur

**Comment by cristim** [comment]
@uguracar that would be great, thanks for volunteering for this.

**Comment by cristim** [comment]
@uguracar I granted you maintainer role on the git repository, that should be enough to allow you to add more people from your team.

**Comment by uguracar** [comment]
perfect, thanks

**Comment by cristim** [comment]
you're welcome, and please take good care of it :-)

**Comment by uguracar** [comment]
sure :) we'll start with the feature requests / issues to build the backlog

**Comment by cristim** [comment]
@uguracar are you still serious about this? It's been almost a month now and I haven't seen any movement so far.

**Comment by uguracar** [comment]
@cristim,  I had a PhD qualifying exam last week and couldn't pass the verbal part:( That's why I was silent. Unfortunately, I'll re-take the exam in the following months so I'll have limited time. This was not my initial plan.  In the meantime, you can search for any other volunteers for leading maintenance work. I'm sorry about this.

**Comment by cristim** [comment]
@uguracar sorry to hear about your failed exam, no worries, I can understand your situation.

Good luck with your second attempt, and looking forward to collaborate afterwards.

I've also seen a few contributions from other people and also getting a little more time myself now that the lockdowns are relaxing here so I hope to resume my work on the event-based branch to bring it up to date and eventually get it merged.
