### ISSUE TITLE
Capacity Rebalancing Support

### ISSUE THREAD

**Issue by gjmveloso** [AutoSpotting/AutoSpotting#448]
## Issue type ##

- Feature Idea

## Summary ##

Have AutoSpotting aware of instance rebalancing feature on ASGs
https://aws.amazon.com/blogs/compute/proactively-manage-spot-instance-lifecycle-using-the-new-capacity-rebalancing-feature-for-ec2-auto-scaling/

## Expected results ##

Better cost savings and proactively manage the Spot Instance lifecycle using the new Capacity Rebalancing feature for EC2 Auto Scaling

**Comment by cristim** [comment]
Thanks for reporting this, we actually talked about this earlier today on Gitter.

At a first glance it should be trivial to get it work by extending the current instance termination notification handling Cloudwatch Event filter.

I don't have time to work on this anytime soon but I would love to see a contribution about this.
