### ISSUE TITLE
SQS Message Group ID too long

### ISSUE THREAD

**Issue by manfredlift** [AutoSpotting/AutoSpotting#470]
https://github.com/AutoSpotting/AutoSpotting/blob/ca139105a9aa995aeb2c339686713c382e5c02e6/core/region.go#L496

I am running into an issue where putting messages on the SQS consistently fails with error:

> ISC:\<instance-id\> 2021/09/14 16:27:44 region.go:501: us-east-1 Error sending on-demand-instance-launch instance \<instance-id\> launch event message to the SQS Queue https://sqs.us-east-1.amazonaws.com/<queue-name\>: InvalidParameterValue: Value us-east-1-\<asg-name\> for parameter MessageGroupId is invalid. Reason: MessageGroupId can only include alphanumeric and punctuation characters. 1 to 128 in length.

Should the AutoSpotting code potentially truncate the `MessageGroupId` to ensure it's less than 128 characters?

**Comment by cristim** [comment]
Yes, probably that could be done. 

I just wonder how come your ASG names are allowed to be so long.

**Comment by cristim** [comment]
@manfredlift The latest release candidate version currently available from the AWS Marketplace should work. You'll need to sign up, install the CloudFormation template and make sure to use `1.0.8-rc4` for the Docker image tag when installing.

I'll release a new official build on the Marketplace over the next few days after I get to test this a bit more.

**Comment by manfredlift** [comment]
> Are you using the stable version available from the AWS marketplace? I'm only actively supporting those users with such bugfixing requests.

No, I am using versions built from source. I understand if this bug fix doesn't get priority -- I was mostly reporting the issue as fixing it might benefit other users as well.

**Comment by cristim** [comment]
Thanks for reporting it, as I said it should be already fixed in the latest stable release candidate.

I just have no reasons to release it to OSS for now. I'll probably only release it later if it ever becomes a maintenance burden to maintain as part of my stable private branch.

**Comment by manfredlift** [comment]
> I just have no reasons to release it to OSS for now. I'll probably only release it later if it ever becomes a maintenance burden to maintain as part of my stable private branch.

@cristim, just to confirm my understanding that new features and bug fixes for AutoSpotting project are closed source from now on?

**Comment by cristim** [comment]
@manfredlift no, I keep developing features in the open, but I offer no bugfixing support for the OSS code.

For the stable builds I have a private branch that I occasionally fork/rebase from the latest version of the OSS code and I maintain in private. It contains some build system changes, as well as bugfixes for bugs I find myself while testing and making a new stable build. These I may sometimes upstream to the OSS code if they become too hard to maintain in that private stable branch, such as if the main branch changes a lot in the same parts of the codebase.

Bug reports are usually only supported/considered if coming from stable users and/or can be reproduced with the latest stable build. And what I do is I implement them on that private stable branch and push a new version to the marketplace that includes the fixes.

**Comment by cristim** [comment]
> @cristim, just to confirm my understanding that new features and bug fixes for AutoSpotting project are closed source from now on?

@manfredlift the main feature I've been working on over the last few weeks has just been pushed as a draft pull request(it's not ready yet but it's been progressing nicely), have a look at https://github.com/AutoSpotting/AutoSpotting/pull/471 to see what I've been up to.
