### ISSUE TITLE
Optionally use Spot Blocks when no spot instance types are cheap enough or the market is too unstable over the last few hours

### ISSUE THREAD

**Issue by cristim** [AutoSpotting/AutoSpotting#78]

**Comment by xlr-8** [comment]
It might sound silly but how would that work?
I haven't played with spot block, but AFAIK spot block are basically spot
instance request with the "blockDuration" parameter.
So I'm not sure to understand how that could be cheaper or effectively
works as you also have to know the duration for which you want them, but
isn't sure to have them directly.

**Comment by cristim** [comment]
This is a fallback option in the relatively rare case in which all the spot prices of compatible instance types are higher than the on-demand price on the AZ where we are about to replace an on-demand instance.

Currently the algorithm would be failing to pick any spot instance type and the group would keep running the given on-demand instance until the spot price of a compatible instance type drops below the on-demand price in that AZ, in which case the instance would get replaced.

Once this feature is implemented, the algorithm would immediately launch a spot block instance set for a configurable duration. These instances are charged a given percentage of the on-demand cost (30-50% off depending on block duration and time of the day), regardless of the normal spot market prices, and are guaranteed to be kept running for that time period, but they would be terminated like any spot instance at the end of the block duration.

Let's say the normal price of the instance is $1/hour, and the market spot price is currently higher than that on all zones. Instead of paying that, we could launch a 6 hours spot block that costs $0.7/hour(we're quite likely in the peak time period anwyay) and is configured to be available for 6hours. The spot block would cost $4.2, plus $1 for that 1 hour of on-demand overlap, so a total of $5.2, which is 13% cheaper than if we were running that on-demand instance for all those 6 hours, which may or may not have happened.

I'm not sure this actually makes enough sense (the gain is relatively small and that assumption may rarely hold true, there is some implementation effort and extra complexity), it was just an idea I had and I wanted to put on the table and have it discussed.

**Comment by xlr-8** [comment]
Oh okay, I see - it does make some sense.

Although it does seem a bit weird to me, as I feel it "breaks" the ASG logic, scaling based on schedule or load, while here we would have a fixed number of hours to launch a spot block.

Maybe the issue could remain, in case it make sense, but be tagged as 'low' or 'reflection', I don't know WDYT?

**Comment by cristim** [comment]
I don't think it breaks anything, AutoScaling can still terminate that spot block instances or launch new ones if needed, it just behaves like any spot instance just that it is guaranteed to be terminated at that given time and it costs a fixed amount of time.

I think this feature makes more sense once we implement something for #3 and #38, in which we're likely not going to start spot instances of a given type if that type was recently outbid in that AZ, in order to reduce the chance for flapping.

For a few hours after the instance was outbid we could launch a spot block of that instance type, and once that's terminated we replace it with a new one if the market is still unstable, or get a normal spot instance if the market has been stable for the last few hours.

**Comment by cristim** [comment]
I think it makes sense to do this in a second pass when iterating over the compatible instance types when implementing #263.

**Comment by cristim** [comment]
This no longer makes much sense, as the market prices are now stable
